// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.0.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// audio_pio //
// --------- //

#define audio_pio_wrap_target 0
#define audio_pio_wrap 11
#define audio_pio_pio_version 0

#define audio_pio_offset_entry_point 11u

static const uint16_t audio_pio_program_instructions[] = {
            //     .wrap_target
    0xb842, //  0: nop                    side 3
    0x7001, //  1: out    pins, 1         side 2
    0xb842, //  2: nop                    side 3
    0x1040, //  3: jmp    x--, 0          side 2
    0xf82f, //  4: set    x, 15           side 3
    0x6001, //  5: out    pins, 1         side 0
    0xa842, //  6: nop                    side 1
    0xa042, //  7: nop                    side 0
    0x0845, //  8: jmp    x--, 5          side 1
    0x7001, //  9: out    pins, 1         side 2
    0xb842, // 10: nop                    side 3
    0xf02e, // 11: set    x, 14           side 2
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program audio_pio_program = {
    .instructions = audio_pio_program_instructions,
    .length = 12,
    .origin = -1,
    .pio_version = audio_pio_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config audio_pio_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + audio_pio_wrap_target, offset + audio_pio_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}

#include "hardware/clocks.h"
static inline void audio_pio_init(PIO pio, uint sm, uint offset,
                                  uint data_pin, uint clock_pin_base,
                                  uint32_t sample_freq)
{
    pio_gpio_init(pio, data_pin);
    pio_gpio_init(pio, clock_pin_base);        // GP26 = BCK
    pio_gpio_init(pio, clock_pin_base + 1);    // GP27 = LRCK
    // GP28 not driven by PIO — set as regular output, held low (don't care)
    pio_sm_config c = audio_pio_program_get_default_config(offset);
    sm_config_set_out_pins(&c, data_pin, 1);
    sm_config_set_set_pins(&c, data_pin, 1);
    sm_config_set_sideset_pins(&c, clock_pin_base);  // base=GP26
    sm_config_set_out_shift(&c, false, true, 32);    // MSB-first, autopull 32
    // clkdiv = sys_clk / (128 × sample_freq)
    // Original program has 128 instructions per frame, BCK = 64×fs
    // At 133 MHz / 44100 Hz: clkdiv=23.56, BCK=2,822,400 Hz ✓
    uint32_t sys_clk = clock_get_hz(clk_sys);
    float    clkdiv  = (float)sys_clk / (128.0f * (float)sample_freq);
    sm_config_set_clkdiv(&c, clkdiv);
    pio_sm_init(pio, sm, offset, &c);
    // Only GP22 and GP26/27 are PIO outputs
    uint pin_mask = (1u << data_pin) | (3u << clock_pin_base);  // 3=0b11, 2 pins
    pio_sm_set_pindirs_with_mask(pio, sm, pin_mask, pin_mask);
    pio_sm_set_pins(pio, sm, 0);
    pio_sm_exec(pio, sm,
                pio_encode_jmp(offset + audio_pio_offset_entry_point));
    pio_sm_set_enabled(pio, sm, true);
}

#endif